### ISSUE TITLE
The scraper is broken

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/clinicaltrials-act-tracker#263]
The scraper is broken.

BennettBot sends notifications to #tech-noise.  The [last notification](https://bennettoxford.slack.com/archives/CGF9TKZLG/p1719808664289129) was sent on July 1st.

![image](https://github.com/user-attachments/assets/9bfde632-ff9d-4e3b-8ee9-7eba3b0fe7ee)

Before that, notifications were sent irregularly.  (Search for `in:#tech-noise "today's data uploaded to fdaaa staging"`.)

This message is sent by the [`load_data` command](https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/3ab17ac9f2aae6f24180128c95eda37616188ba1/clinicaltrials/frontend/management/commands/load_data.py#L195-L198).  Given [this try/except block](https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/3ab17ac9f2aae6f24180128c95eda37616188ba1/clinicaltrials/frontend/management/commands/load_data.py#L214-L222) I'm a bit surprised that we haven't also seen "Error in FDAAA import" messages, but we haven't seen those since January 2020.

The scraper is deployed to smallweb1:/var/www/fdaaa_staging/clinicaltrials-act-tracker.  However, the checked-out branch is [gae-ise](https://github.com/ebmdatalab/clinicaltrials-act-tracker/tree/gae-ise) and not master.  And this has a very different version of the [`load_data` command](https://github.com/ebmdatalab/clinicaltrials-act-tracker/blob/7f4260bbbc9b10a4db0d0d5f5e111ac737c77fa0/clinicaltrials/frontend/management/commands/load_data.py), which doesn't directly notify Slack.

There's a cronjob that runs at 4am UTC on weekdays that calls the `load_data` command:

```
$ cat /etc/cron.d/fdaaa 
# This cronjob imports data into the clinicaltrials_staging db
# which Nick DeVito checks & then copies to production
00 04 * * 1-5 seb /usr/local/bin/fdaaa_temp.sh
```

That runs this script:

```
$ cat /usr/local/bin/fdaaa_temp.sh
#!/bin/bash

set -e

. /etc/profile.d/fdaaa_staging.sh
GOOGLE_SERVICE_ACCOUNT_FILE=/home/seb/clinicaltrials-credentials.json GOOGLE_SERVICE_ACCOUNT_FILE_FDAAA=$GOOGLE_SERVICE_ACCOUNT_FILE /var/www/fdaaa_staging/venv/bin/python /var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/manage.py load_data staging-fdaaa.ebmdatalab.net
```

This calls `load_data`.  And in `smallweb1:/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/frontend/clinicaltrials.log` we see this line:

```
2024-09-16 03:00:07 [2090667] [INFO] pathname=/var/www/fdaaa_staging/venv/lib/python3.5/site-packages/googleapiclient/discovery.py lineno=873 funcname=method URL being requested: GET https://compute.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10?alt=json
```

If we run the script directly, we get an error:

```
$ /usr/local/bin/fdaaa_temp.sh
Traceback (most recent call last):
  File "/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/fdaaa_staging/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/www/fdaaa_staging/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/fdaaa_staging/venv/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/fdaaa_staging/venv/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/frontend/management/commands/load_data.py", line 32, in handle
    "ebmdatalab", "europe-west2-a", "ctgov-converter", callback, wait=False
  File "/var/www/fdaaa_staging/venv/src/clinicaltrials-act-converter/ctconvert/create_instance.py", line 164, in main
    operation = create_instance(compute, project, zone, instance_name, callback)
  File "/var/www/fdaaa_staging/venv/src/clinicaltrials-act-converter/ctconvert/create_instance.py", line 20, in create_instance
    .getFromFamily(project="debian-cloud", family="debian-10")
  File "/var/www/fdaaa_staging/venv/lib/python3.5/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/var/www/fdaaa_staging/venv/lib/python3.5/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://compute.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10?alt=json returned "The resource 'projects/debian-cloud/global/images/family/debian-10' was not found">
```

**Comment by madwort** [comment]
This was a problem with `clinicaltrials-act-converter`, and was because debian 10 lts was eol & google removed the image. 

[This is the previous time this happened (with debian 9)](https://github.com/ebmdatalab/clinicaltrials-act-converter/issues/15).

[This is the fix, an upgrade to debian 12](https://github.com/ebmdatalab/clinicaltrials-act-converter/pull/21).
